// Autogenerated from Pigeon (v17.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

class PEkycRequest {
  PEkycRequest({
    required this.countryCode,
    required this.idType,
    required this.backCamera,
  });

  String countryCode;

  String idType;

  bool backCamera;

  Object encode() {
    return <Object?>[
      countryCode,
      idType,
      backCamera,
    ];
  }

  static PEkycRequest decode(Object result) {
    result as List<Object?>;
    return PEkycRequest(
      countryCode: result[0]! as String,
      idType: result[1]! as String,
      backCamera: result[2]! as bool,
    );
  }
}

class PEkycConfig {
  PEkycConfig({
    required this.token,
    required this.endpoint,
  });

  String token;

  String endpoint;

  Object encode() {
    return <Object?>[
      token,
      endpoint,
    ];
  }

  static PEkycConfig decode(Object result) {
    result as List<Object?>;
    return PEkycConfig(
      token: result[0]! as String,
      endpoint: result[1]! as String,
    );
  }
}

class _EkycHostApiCodec extends StandardMessageCodec {
  const _EkycHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PEkycConfig) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PEkycRequest) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PEkycConfig.decode(readValue(buffer)!);
      case 129: 
        return PEkycRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class EkycHostApi {
  /// Constructor for [EkycHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  EkycHostApi({BinaryMessenger? binaryMessenger})
      : __pigeon_binaryMessenger = binaryMessenger;
  final BinaryMessenger? __pigeon_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _EkycHostApiCodec();

  Future<String> getPlatformVersion() async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.wise_ai_ekyc.EkycHostApi.getPlatformVersion';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(null) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }

  Future<void> initialize(PEkycConfig config) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.wise_ai_ekyc.EkycHostApi.initialize';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[config]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<String> performEkyc(PEkycRequest request) async {
    const String __pigeon_channelName = 'dev.flutter.pigeon.wise_ai_ekyc.EkycHostApi.performEkyc';
    final BasicMessageChannel<Object?> __pigeon_channel = BasicMessageChannel<Object?>(
      __pigeon_channelName,
      pigeonChannelCodec,
      binaryMessenger: __pigeon_binaryMessenger,
    );
    final List<Object?>? __pigeon_replyList =
        await __pigeon_channel.send(<Object?>[request]) as List<Object?>?;
    if (__pigeon_replyList == null) {
      throw _createConnectionError(__pigeon_channelName);
    } else if (__pigeon_replyList.length > 1) {
      throw PlatformException(
        code: __pigeon_replyList[0]! as String,
        message: __pigeon_replyList[1] as String?,
        details: __pigeon_replyList[2],
      );
    } else if (__pigeon_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (__pigeon_replyList[0] as String?)!;
    }
  }
}
